# URL de conexión (reemplaza 'nombre_tu_bd' por el nombre real)
spring.datasource.url=jdbc:mysql://localhost:3306/asistenciaescolar?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
# Credenciales de acceso
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

# Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Estrategia de Hibernate para la creación de tablas
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto para MySQL 8 o superior
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Obliga a Hibernate a usar los nombres exactos definidos en @Table y @Column
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Evita que se intente procesar el nombre antes de aplicar la estrategia física
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

# CONFIGURACIÓN DE CLOUDINARY
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
spring.servlet.multipart.resolve-lazily=true
# Tamaño máximo permitido para cada archivo individual (ej. 10MB)
spring.servlet.multipart.max-file-size=10MB
# Tamaño máximo total permitido para toda la petición multipart (ej. 10MB)
spring.servlet.multipart.max-request-size=10MB
logging.level.org.springdoc=DEBUG

api.dni.token=${API_TOKEN}
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true


# Configuración de Twilio mapeada a variables de entorno
twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.phone.number=${TWILIO_PHONE_NUMBER}